### ISSUE TITLE
Downloading playlists.

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#29]
Users should be able to download YouTube playlists, it would be a very nice feature to add to the application .

**Comment by jdrysdaleandesrson** [comment]
Issue has been fixed on news pull request

**Comment by AlbertSolomon** [comment]
@jdrysdaleandesrson 👋🏾 The fix is not complete; this is because the user is not being informed properly in the UI on what's going on during the download process of the playlist, therefore the issue has been partially fixed 😃.
